Feature/user auth
evgen-kent/AZATI_Workshop_BE pull request #5
Opened 2023-12-20 18:08 UTC by SergeyMurin

Requests
[<img src="https://run.pstmn.io/button.svg" alt="Run In Postman" style="width: 128px; height: 32px;">](https://app.getpostman.com/run-collection/21760073-a3c704f8-6609-46a7-b547-8c8933e9d9f8?action=collection%2Ffork&source=rip_markdown&collection-url=entityId%3D21760073-a3c704f8-6609-46a7-b547-8c8933e9d9f8%26entityType%3Dcollection%26workspaceId%3D77726a00-3b55-44b9-93f1-abec8b36e911)

2023-12-20 18:30 UTC, AlesiaKlemenia approved these changes

2023-12-20 18:52 UTC, evgen-kent commented on src/modules/auth/auth.controller.ts
> +  //@UseGuards(LocalAuthGuard)
Опиши плиз подробнее в чем недостаток текущего варианта и что улучшает твой вариант

2023-12-20 18:56 UTC, SergeyMurin commented on src/modules/auth/auth.controller.ts
> +  //@UseGuards(LocalAuthGuard)
Это же вроде логично. Разве нет? Чтобы залогиниться пользователю, ему не нужно быть залогиненым заранее и иметь токен.

2023-12-21 10:37 UTC, evgen-kent requested changes
надо декомпозировать пр на атомарные части, к каждой чаcти завести задачу и прилинковать к ней пр.  В задачах расписать DOR (destination of ready)

2023-12-21 15:21 UTC, closed without merging